# 11 - Matrices and Higher-Dimensional Arrays

## 11.1 - Creating Matrices with NumPy

Here are a few methdos for creating matrices with NumPy:
- `np.array()`
- `np.zeros()` and `np.ones()`
- `np.eye()`
- `np.random`

### Convert a Table (Nested List) to a Matrix with NumPy

To convert a table (a nested list) into a matrix with NumPy, you can use the `np.array()` function. This function takes a list (or a nested list for 2D arrays) as its argument and returns a NumPy array representing the matrix

In [2]:
import numpy as np

table = [[1, 2, 3, 4], [5, 6, 7, 8]]
np.array(table)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Zeros, Ones, and Identity Matrices

In [3]:
# Create a 2x3 matrix of zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# Create a 3x2 matrix of ones
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Random Matrices

In [7]:
# Create 2x4 matrix of random variables
np.random.rand(2,4)

array([[0.73242379, 0.1912915 , 0.53698183, 0.02708391],
       [0.87340142, 0.41230862, 0.82836447, 0.55014607]])

## 11.2 - Slicing and Indexing in NumPy Arrays

### Indexing

You can access the $(i,j)$-th entry of matrix `a` using `a[i,j]`.

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a[1,2], a[0, 0], a[2, 1]

(6, 1, 8)

You can access an entire row or column by specifying the index for one dimension or using colon `:` for the other.

In [14]:
# Access the second column
a[:, 1]

array([2, 5, 8])

In [15]:
# Access the first row
a[0, :]

array([1, 2, 3])

### Slicing

Slicing can be used to get a subset of an array. Specify the start and end indices for each dimension, separated by a colon.

In [16]:
a[0:2, 1:3]

array([[2, 3],
       [5, 6]])

### Modifying Elements

In [17]:
a[0, 0] = 10
a

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
# Modify a subarray
a[0:2, 0:2] = np.array([[11, 12], [13, 14]])
a

array([[11, 12,  3],
       [13, 14,  6],
       [ 7,  8,  9]])

## 11.3 - Matrix Operations

### Addition and Subtraction

In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = a + b
c

array([[ 6,  8],
       [10, 12]])

In [21]:
d = a - b
d

array([[-4, -4],
       [-4, -4]])

### Scalar Multiplication

### Dot and Cross Products

### Element-Wise Multiplication

### Matrix Multiplication

### Transpose of a Matrix

### Determinant

### Inverse

### Rank

## 11.4 - Graphs, Adjacency Matrix, and Distinct Walks

### Graphs



### Adjacency Matrix



### Distinct Walks of $n$



### Public Transit System: Bus Stations and Connections

## 11.5 - Images as Matrices

### Numerical Representation of Images

### Working with Real Images

### Blurring an Image

### Some Useful Tips for Working with Images